// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalcPixDens(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalcPixDens'](arg1, arg2, arg3);
}

export function CalcSensorRatio(arg1, arg2) {
  return window['go']['main']['App']['CalcSensorRatio'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
